# Generated by Django 3.2.5 on 2021-08-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sino', '0002_auto_20210822_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SA',
            new_name='Person',
        ),
    ]
