# Generated by Django 3.2.5 on 2021-08-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sino', '0003_rename_sa_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Outdoor'), ('Out door', 'IN door')], max_length=255, null=True),
        ),
    ]
