# Generated by Django 3.2.5 on 2021-08-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Username..', max_length=255)),
                ('type', models.CharField(default='Type of Product..', max_length=244)),
                ('requirements', models.CharField(default='Requirement of products', max_length=255)),
            ],
        ),
    ]
